spring.application.name=musify

server.port=8080

#Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/musify_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



# JWT Configuration
jwt.secret=musifySecretKeyForJWTTokenGenerationAndValidationPleaseChangeThisInProduction12345
jwt.access.token.expiration=1800000 # 30 minutes
jwt.refresh.token.expiration=604800000 # 7 days

#File Storage Configuration
file.storage.song.path=uploads/songs
file.storage.image.path=uploads/images
app.base.url=http://localhost:8080

# Multipart File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testappfunction@gmail.com
spring.mail.password=faciytkvnoyvgfbs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Frontend URL Configuration
app.frontend.url=http://localhost:4200

# Gemini API key
gemini.api.key=AIzaSyBpOgBN1dP9jbLHLQ2IEv87SpDxk_tIEcY
gemini.models=gemini-2.5-flash-lite,gemini-2.0-flash-lite,gemini-2.5-flash,gemini-2.0-flash-exp